version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq-ms
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:management

  users_db:
    container_name: user-db-pg
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_db

  # orders_db:
  #   container_name: user-db-pg
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: user_db

  # products_db:
  #   container_name: user-db-pg
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: user_db

  # mail_db:
  #   container_name: user-db-pg
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: user_db

