version: '3.8'
services:
    rabbitmq:
        image:rabbitmq:management
    user_db_pg:
      image:postgres:latest

    products_db_pg:
      image:postgres:latest
    orders_db_pg:
      image:postgres:latest
    mail_db_cassandra:
    nginx:
