version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq-ms
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:management
  
  
  user_db_pg:
    container_name: user-db-pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    # products_db_pg:
    #   image:postgres:latest
    # orders_db_pg:
    #   image:postgres:latest
    # mail_db_cassandra:
    # nginx:
