version: '3.8'
services:
  user_db_pg:
    container_name: user-db-pg
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_db
#     networks:
#       - nestjs_network
# networks:
#   nestjs_network:
#     driver: bridge
